[package]
name = "bin"
version = "1.0.1"
authors = ["Jordan Doyle <jordan@doyle.la>"]
edition = "2018"

[dependencies]
linked-hash-map = "0.5"
rocket = "0.4"
askama = { git = "https://github.com/djc/askama", rev = "fc5addc4", features = ["with-rocket"] }
askama_escape = { git = "https://github.com/djc/askama", rev = "fc5addc4" }
lazy_static = "1.2"
rand = "0.6"
gpw = "0.1"
syntect = "3.0"
serde_derive = { version = "1.0" }

[profile.release]
lto = true
codegen-units = 1
incremental = false