[package]
name = "bin"
version = "1.0.1"
authors = ["Jordan Doyle <jordan@doyle.la>"]
edition = "2018"

[dependencies]
linked-hash-map = "0.5"
rocket = { version = "0.4", default-features = false }
askama = "0.7"
lazy_static = "1.2"
rand = { version = "0.6", features = ["nightly"] }
gpw = "0.1"
syntect = "3.0"
serde_derive = "1.0"

[profile.release]
lto = true
codegen-units = 1
incremental = false