[package]
name = "bin"
version = "0.1.0"
authors = ["Jordan Doyle <jordan@doyle.la>"]
edition = "2018"

[dependencies]
rocket = "0.4"
lazy_static = "1.2"
gpw = "0.1"
syntect = "3.0"
chashmap = { git = "https://github.com/redox-os/tfs" }
serde = { version = "1.0", features = ["derive"] }

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["tera_templates"]